version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped
volumes:
  supabase-data:
